### ISSUE TITLE
"Previously Located Error" with custom SSH port

### ISSUE THREAD

**Issue by Snooper125** [KenKundert/emborg#27]
CREATE BACKUP WITH PORT 2222 WITH BORG
borg --verbose init --encryption=none test
sudo borg create --list --show-rc --verbose --progress --stats --comment "Backup Now." ssh://server@mydomain.com:2222/test::Backup-{now:%Y-%m-%dT%H:%M:%S.%f} /home/test

INFO ON BACKUP USING EMBORG OR ANY COMMAND
Note:Using ssh_command = "ssh -p 2222"
emborg info

Warning: The repository at location ssh://server@mydomain.com/test was previously located at ssh://server@mydomain.com:2222/test
    Do you want to continue? [yN] Aborting.
    Repository access aborted

The Emborg Repository location won't include the port and borg will see it as a different location.

I tried:
export BORG_RELOCATED_REPO_ACCESS_IS_OK=no

with limited success and would prefer not to if there is a better option.

**Comment by KenKundert** [comment]
Did you look at the emborg log file and see if the BORG_RSH environment variable is set properly.

This issue does not come up for me even though I use odd SSH ports because I create an entry in my ssh config file for the host that includes the port and any other thing I need. Then I just use a simple host name in emborg. You might want to try that.

**Comment by Snooper125** [comment]
Hello Ken,

Thanks for response.

My BORG_RSH was not passing to SUDO properly.

Thanks,
Darrell

________________________________
