### ISSUE TITLE
Allow use of {health} when displaying archive contents

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/emborg#40]
There is no way to use the {health} format specifier when using the 'manifest' command in emborg.

It would be useful if this could be added.

**Comment by KenKundert** [comment]
Your right, that does seem useful. I'll work on it.

**Comment by KenKundert** [comment]
I have just updated Emborg on github. I have reworked the manifest command so that all, or at least most, of the Borg field names are supported. None of the built-in formats include {health}, but you can use *manifest_formats* to create your own that does.  However, I now colorize the output from manifest.  If the line is green, the file is healthy.  If it is read, the file is broken.

Please give it a try and see if it meets your needs.

**Comment by adhawkins** [comment]
Looks just the job. Can you make an 'official' release of this? I'm the maintainer of the alpine package, so I'll get it updated.

**Comment by KenKundert** [comment]
Okay I have updated to version 1.21 and have uploaded it to pypi.org.
Thanks!
